robot_NQJ=6
robot_NJ=6
robot_name="CloosQRC350OL"
robot_NL=7
robot_gVec=0,0,1
robot_NKP=6
robot_KP="L1 L2 L3 L4 L5 L6"
robot_kinconstr_exist=0
robot_NKCP=0
robot_KCP=""
robot_NMPVFIXB=19
robot_NMPVFLOATB=NOTDEFINED
robot_NTAUJFIXBREGNN=63
